package com.inaki.micoche;
import android.Manifest;import android.app.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;
import android.graphics.Bitmap;import android.location.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;
import android.view.*;import android.webkit.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.concurrent.Executor;
public class MainActivity extends Activity {
 public static final String ACTION_SAVE_NOW="com.inaki.micoche.SAVE_NOW",ACTION_PARKING_NOW="com.inaki.micoche.PARKING_NOW",ACTION_RESOLVE_PARKING="com.inaki.micoche.RESOLVE_PARKING";
 private static final int LOC=10,CAM=30,BT=31; private LocationManager lm; private WebView map; private TextView status,address,coords,ago; private ImageView car; private Button nav; private boolean afterPermissionParking=false;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);lm=(LocationManager)getSystemService(LOCATION_SERVICE);bind();AutoParkingManager.createNotificationChannel(this);AutoParkingManager.ensureObservation(this);refresh();handle(getIntent());}
 private void bind(){map=findViewById(R.id.mapWeb);car=findViewById(R.id.mapCar);status=findViewById(R.id.statusTitle);address=findViewById(R.id.addressText);coords=findViewById(R.id.coordsText);ago=findViewById(R.id.savedAgo);nav=findViewById(R.id.navButton);
  map.getSettings().setJavaScriptEnabled(true);findViewById(R.id.saveButton).setOnClickListener(v->saveHere());findViewById(R.id.parkingButton).setOnClickListener(v->parkingFlow());nav.setOnClickListener(v->navigate());findViewById(R.id.settingsButton).setOnClickListener(v->settings());
 }
 private void handle(Intent i){if(i==null)return;String a=i.getAction();if(ACTION_SAVE_NOW.equals(a))new Handler().postDelayed(this::saveHere,200);else if(ACTION_PARKING_NOW.equals(a))new Handler().postDelayed(this::parkingFlow,200);else if(ACTION_RESOLVE_PARKING.equals(a))new Handler().postDelayed(this::showNoGpsChoices,250);}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handle(i);}
 private boolean perm(){return checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;}
 private void fresh(java.util.function.Consumer<Location> cb){if(!perm()){cb.accept(null);return;}try{lm.getCurrentLocation(LocationManager.GPS_PROVIDER,null,getMainExecutor(),cb::accept);}catch(Exception e){cb.accept(null);}}
 private void saveHere(){if(!perm()){afterPermissionParking=false;requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOC);return;}fresh(l->{if(l==null){Toast.makeText(this,"No he podido obtener GPS",Toast.LENGTH_LONG).show();return;}saveLocation(l,CarStorage.SOURCE_MANUAL);});}
 private void parkingFlow(){if(!perm()){afterPermissionParking=true;requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOC);return;}
  final long started=System.currentTimeMillis();fresh(l->{if(l!=null&&l.getTime()>=started){saveLocation(l,CarStorage.SOURCE_MANUAL);Toast.makeText(this,"Parking guardado con GPS nuevo ✓",Toast.LENGTH_SHORT).show();}else showNoGpsChoices();});}
 private void showNoGpsChoices(){String[] o={"Casa","Casa 2","Trabajo","Hacer foto"};new AlertDialog.Builder(this).setTitle("No tengo GPS").setMessage("¿Dónde has aparcado?").setItems(o,(d,w)->{if(w==0)garage("home","Casa");else if(w==1)garage("home2","Casa 2");else if(w==2)garage("work","Trabajo");else camera();}).setNegativeButton("Cancelar",null).show();}
 private void garage(String k,String title){if(!GaragePrefs.has(this,k)){Toast.makeText(this,title+" no tiene posición guardada. Haz una foto.",Toast.LENGTH_LONG).show();camera();return;}CarStorage.save(this,GaragePrefs.lat(this,k),GaragePrefs.lon(this,k),title+" · parking",System.currentTimeMillis(),CarStorage.SOURCE_GARAGE);AutoParkingPrefs.setParkingPending(this,false);refresh();CarWidgetProvider.updateAll(this);}
 private void camera(){Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);if(i.resolveActivity(getPackageManager())!=null)startActivityForResult(i,CAM);else Toast.makeText(this,"No hay cámara disponible",Toast.LENGTH_LONG).show();}
 @Override protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==CAM&&result==RESULT_OK){Bitmap bm=data==null?null:(Bitmap)data.getExtras().get("data");if(bm!=null)try(FileOutputStream f=openFileOutput("parking_photo.jpg",MODE_PRIVATE)){bm.compress(Bitmap.CompressFormat.JPEG,92,f);}catch(Exception ignored){}AutoParkingPrefs.setParkingPending(this,false); CarWidgetProvider.updateAll(this); Toast.makeText(this,"Foto del parking guardada ✓",Toast.LENGTH_LONG).show();}}
 private void saveLocation(Location l,String source){double la=l.getLatitude(),lo=l.getLongitude();long t=System.currentTimeMillis();CarStorage.save(this,la,lo,String.format(Locale.US,"%.6f, %.6f",la,lo),t,source);refresh();CarWidgetProvider.updateAll(this);new Thread(()->{try{List<Address>a=new Geocoder(this,new Locale("es","ES")).getFromLocation(la,lo,1);if(a!=null&&!a.isEmpty()){String s=a.get(0).getAddressLine(0);runOnUiThread(()->{CarStorage.save(this,la,lo,s,t,source);refresh();CarWidgetProvider.updateAll(this);});}}catch(Exception ignored){}}).start();}
 private void refresh(){boolean h=CarStorage.hasCar(this);nav.setEnabled(h);car.setVisibility(h?View.VISIBLE:View.GONE);if(!h){status.setText("Coche no guardado");address.setText("Todavía no hay una ubicación guardada");coords.setText("");ago.setText("Guarda aquí o usa Parking");load(42.06,-1.60,false);return;}status.setText("Coche guardado");address.setText(CarStorage.address(this));coords.setText(String.format(Locale.US,"%.6f, %.6f",CarStorage.lat(this),CarStorage.lon(this)));ago.setText(CarStorage.SOURCE_AUTO.equals(CarStorage.source(this))?"Automático · GPS posterior al Bluetooth":"Ubicación guardada");load(CarStorage.lat(this),CarStorage.lon(this),true);}
 private void load(double la,double lo,boolean saved){String u=String.format(Locale.US,"https://www.openstreetmap.org/export/embed.html?bbox=%.6f%%2C%.6f%%2C%.6f%%2C%.6f&layer=mapnik",lo-.0065,la-.0045,lo+.0065,la+.0045);map.loadUrl(u);if(saved)car.setImageResource(R.drawable.car_log);}
 private void navigate(){if(!CarStorage.hasCar(this))return;startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("google.navigation:q="+CarStorage.lat(this)+","+CarStorage.lon(this)+"&mode=w")));}
 private void settings(){View v=getLayoutInflater().inflate(R.layout.dialog_settings,null);AlertDialog d=new AlertDialog.Builder(this).setView(v).setPositiveButton("Cerrar",null).create();
  v.findViewById(R.id.homeButton).setOnClickListener(x->saveGarage("home","Casa"));v.findViewById(R.id.home2Button).setOnClickListener(x->saveGarage("home2","Casa 2"));v.findViewById(R.id.workButton).setOnClickListener(x->saveGarage("work","Trabajo"));v.findViewById(R.id.bluetoothButton).setOnClickListener(x->chooseBluetooth());((TextView)v.findViewById(R.id.autoStatus)).setText(AutoParkingPrefs.lastEvent(this));d.show();}
 private void saveGarage(String k,String title){if(!perm()){Toast.makeText(this,"Concede ubicación y vuelve a pulsar",Toast.LENGTH_LONG).show();requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},LOC);return;}fresh(l->{if(l==null){Toast.makeText(this,"Sin GPS",Toast.LENGTH_SHORT).show();return;}GaragePrefs.save(this,k,l.getLatitude(),l.getLongitude(),l.hasAccuracy()?l.getAccuracy():0);Toast.makeText(this,title+" guardado",Toast.LENGTH_SHORT).show();});}
 private void chooseBluetooth(){if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT},BT);return;}BluetoothManager m=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE);Set<BluetoothDevice>s=m.getAdapter().getBondedDevices();if(s.isEmpty()){Toast.makeText(this,"No hay Bluetooth emparejado",Toast.LENGTH_LONG).show();return;}List<BluetoothDevice>l=new ArrayList<>(s);String[]n=new String[l.size()];for(int i=0;i<l.size();i++){try{n[i]=l.get(i).getName();}catch(Exception e){n[i]=l.get(i).getAddress();}}new AlertDialog.Builder(this).setTitle("Bluetooth de mi coche").setItems(n,(d,w)->{BluetoothDevice x=l.get(w);String name=n[w];AutoParkingPrefs.configure(this,x.getAddress(),name);AutoParkingManager.ensureObservation(this);Toast.makeText(this,"Bluetooth configurado",Toast.LENGTH_SHORT).show();}).show();}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==LOC&&perm()){if(afterPermissionParking){afterPermissionParking=false;parkingFlow();}else saveHere();}else if(r==BT)chooseBluetooth();}
}
